import type { Place } from './types'

export const DEMO_CITY = 'Bengaluru'

export const CITY_CONDITIONS = {
  weather: { tempC: 27, label: 'Partly cloudy', rainAfter: 16, rainChance: 60 },
  traffic: { level: 'Moderate', note: 'Peak congestion 5–8 PM on Outer Ring Road' },
  safety: { level: 'Good', note: 'Central areas well-lit and patrolled' },
}

export const EMERGENCY_NUMBERS = [
  { label: 'All emergencies', number: '112', primary: true },
  { label: 'Police', number: '100' },
  { label: 'Ambulance', number: '108' },
  { label: 'Fire', number: '101' },
  { label: 'Women helpline', number: '1091' },
]

/** Mock places for the demo city. Shaped so a real Places API response can be mapped onto it later. */
export const PLACES: Place[] = [
  {
    id: 'bangalore-palace',
    name: 'Bangalore Palace',
    category: 'attraction',
    area: 'Vasanth Nagar',
    description: 'Tudor-style royal palace with carved interiors and an audio tour.',
    tags: ['history', 'art'],
    personas: ['tourist', 'family'],
    rating: 4.4,
    cost: 500,
    x: -1,
    y: 4,
    opens: '10:00',
    closes: '17:30',
    durationMin: 90,
    crowd: 'medium',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: false,
    plannable: true,
  },
  {
    id: 'tipu-palace',
    name: "Tipu Sultan's Summer Palace",
    category: 'attraction',
    area: 'Chamrajpet',
    description: 'An 18th-century teak palace with painted arches and a small museum.',
    tags: ['history'],
    personas: ['tourist', 'student'],
    rating: 4.2,
    cost: 50,
    x: -2.5,
    y: -3,
    opens: '08:30',
    closes: '17:30',
    durationMin: 60,
    crowd: 'medium',
    safety: 'high',
    accessible: false,
    outdoor: true,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'lalbagh',
    name: 'Lalbagh Botanical Garden',
    category: 'place',
    area: 'Lalbagh',
    description: '240 acres of gardens, a glasshouse and a 3,000-million-year-old rock.',
    tags: ['nature', 'history', 'kids'],
    personas: ['tourist', 'family', 'student'],
    rating: 4.5,
    cost: 30,
    x: 0,
    y: -4,
    opens: '06:00',
    closes: '19:00',
    durationMin: 90,
    crowd: 'high',
    safety: 'high',
    accessible: true,
    outdoor: true,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'cubbon-park',
    name: 'Cubbon Park',
    category: 'place',
    area: 'Central',
    description: 'Leafy central park with jogging trails, bamboo groves and weekend markets.',
    tags: ['nature', 'fitness', 'kids'],
    personas: ['family', 'student', 'professional', 'tourist'],
    rating: 4.6,
    cost: 0,
    x: -0.5,
    y: 0.5,
    opens: '06:00',
    closes: '20:00',
    durationMin: 60,
    crowd: 'low',
    safety: 'high',
    accessible: true,
    outdoor: true,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'vidhana-soudha',
    name: 'Vidhana Soudha',
    category: 'attraction',
    area: 'Ambedkar Veedhi',
    description: 'The granite seat of the state legislature, beautifully lit on Sunday evenings.',
    tags: ['history'],
    personas: ['tourist', 'student'],
    rating: 4.5,
    cost: 0,
    x: -1.2,
    y: 1,
    opens: '07:00',
    closes: '21:00',
    durationMin: 30,
    crowd: 'low',
    safety: 'high',
    accessible: true,
    outdoor: true,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'ngma',
    name: 'National Gallery of Modern Art',
    category: 'attraction',
    area: 'Palace Road',
    description: 'Modern Indian art in a quiet colonial mansion with a lovely café.',
    tags: ['art', 'history'],
    personas: ['tourist', 'student'],
    rating: 4.4,
    cost: 20,
    x: -1,
    y: 3,
    opens: '10:00',
    closes: '17:00',
    durationMin: 75,
    crowd: 'low',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: false,
    plannable: true,
  },
  {
    id: 'vitm',
    name: 'Visvesvaraya Tech Museum',
    category: 'attraction',
    area: 'Kasturba Road',
    description: 'Hands-on science and engineering galleries, from engines to space.',
    tags: ['tech', 'kids'],
    personas: ['family', 'student'],
    rating: 4.5,
    cost: 85,
    x: -0.8,
    y: 0.8,
    opens: '09:30',
    closes: '18:00',
    durationMin: 120,
    crowd: 'medium',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'bugle-rock',
    name: 'Bugle Rock Park',
    category: 'attraction',
    area: 'Basavanagudi',
    description: 'Ancient rock outcrop and watchtower, perfect for a calm sunset view.',
    tags: ['viewpoint', 'nature', 'history'],
    personas: ['tourist', 'family'],
    rating: 4.3,
    cost: 0,
    x: -2,
    y: -6,
    opens: '06:00',
    closes: '20:00',
    durationMin: 45,
    crowd: 'low',
    safety: 'medium',
    accessible: false,
    outdoor: true,
    nearMetro: false,
    plannable: true,
  },
  {
    id: 'ulsoor-lake',
    name: 'Ulsoor Lake Promenade',
    category: 'attraction',
    area: 'Ulsoor',
    description: 'Lakeside walk with boating and golden-hour views over the water.',
    tags: ['viewpoint', 'nature', 'fitness'],
    personas: ['tourist', 'professional', 'family'],
    rating: 4.1,
    cost: 0,
    x: 1.8,
    y: 1.5,
    opens: '06:00',
    closes: '20:30',
    durationMin: 45,
    crowd: 'low',
    safety: 'high',
    accessible: true,
    outdoor: true,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'mtr',
    name: 'MTR Lalbagh Road',
    category: 'food',
    area: 'Lalbagh Road',
    description: 'Legendary since 1924 — rava idli, masala dosa and filter coffee.',
    tags: ['food', 'history'],
    personas: ['tourist', 'family'],
    rating: 4.5,
    cost: 300,
    x: 0.3,
    y: -3.5,
    opens: '06:30',
    closes: '21:30',
    durationMin: 60,
    crowd: 'high',
    safety: 'high',
    accessible: false,
    outdoor: false,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'vidyarthi-bhavan',
    name: 'Vidyarthi Bhavan',
    category: 'food',
    area: 'Basavanagudi',
    description: 'Crispy butter masala dosas served the same way since 1943.',
    tags: ['food', 'history'],
    personas: ['tourist', 'student'],
    rating: 4.6,
    cost: 150,
    x: -2,
    y: -5.5,
    opens: '06:30',
    closes: '20:00',
    durationMin: 45,
    crowd: 'high',
    safety: 'high',
    accessible: false,
    outdoor: false,
    nearMetro: false,
    plannable: true,
  },
  {
    id: 'brahmins',
    name: "Brahmin's Coffee Bar",
    category: 'food',
    area: 'Shankarapuram',
    description: 'Stand-and-eat idli, vada and strong coffee for under ₹100.',
    tags: ['food', 'quick'],
    personas: ['student', 'tourist'],
    rating: 4.6,
    cost: 80,
    x: -3,
    y: -5,
    opens: '06:00',
    closes: '13:00',
    durationMin: 30,
    crowd: 'high',
    safety: 'high',
    accessible: false,
    outdoor: false,
    nearMetro: false,
    plannable: true,
  },
  {
    id: 'koshys',
    name: "Koshy's",
    category: 'food',
    area: 'St. Marks Road',
    description: 'Old-school café loved by writers and office-goers since 1940.',
    tags: ['food', 'history', 'work'],
    personas: ['professional', 'tourist'],
    rating: 4.3,
    cost: 600,
    x: -0.2,
    y: 0.3,
    opens: '09:00',
    closes: '23:00',
    durationMin: 60,
    crowd: 'medium',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'rameshwaram',
    name: 'Rameshwaram Cafe',
    category: 'food',
    area: 'Indiranagar',
    description: 'Fast, buzzing South Indian counter — ghee podi idli in minutes.',
    tags: ['food', 'quick'],
    personas: ['professional', 'student'],
    rating: 4.4,
    cost: 200,
    x: 4.2,
    y: 1,
    opens: '06:00',
    closes: '23:59',
    durationMin: 30,
    crowd: 'high',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'nagarjuna',
    name: 'Nagarjuna',
    category: 'food',
    area: 'Residency Road',
    description: 'Spacious Andhra meals restaurant with high chairs and quick service.',
    tags: ['food'],
    personas: ['family', 'professional'],
    rating: 4.3,
    cost: 500,
    x: 0.5,
    y: -0.3,
    opens: '12:00',
    closes: '23:00',
    durationMin: 60,
    crowd: 'medium',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'toit',
    name: 'Toit Brewpub',
    category: 'food',
    area: 'Indiranagar',
    description: 'Iconic craft brewery with wood-fired pizzas and a lively crowd.',
    tags: ['nightlife', 'food'],
    personas: ['professional', 'tourist'],
    rating: 4.5,
    cost: 1500,
    x: 4,
    y: 0.5,
    opens: '12:00',
    closes: '23:30',
    durationMin: 90,
    crowd: 'high',
    safety: 'medium',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'central-library',
    name: 'State Central Library',
    category: 'place',
    area: 'Cubbon Park',
    description: 'Quiet red Gothic library inside Cubbon Park. Free reading rooms.',
    tags: ['study', 'history'],
    personas: ['student'],
    rating: 4.4,
    cost: 0,
    x: -0.6,
    y: 0.7,
    opens: '08:30',
    closes: '19:30',
    durationMin: 120,
    crowd: 'low',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'dyu-cafe',
    name: 'Dyu Art Cafe',
    category: 'place',
    area: 'Koramangala',
    description: 'Calm courtyard café with good Wi-Fi, art on the walls and great coffee.',
    tags: ['study', 'art', 'food'],
    personas: ['student', 'professional'],
    rating: 4.5,
    cost: 350,
    x: 2,
    y: -4.5,
    opens: '10:00',
    closes: '22:00',
    durationMin: 90,
    crowd: 'low',
    safety: 'high',
    accessible: false,
    outdoor: false,
    nearMetro: false,
    plannable: true,
  },
  {
    id: 'springboard',
    name: '91springboard Co-working',
    category: 'place',
    area: 'Koramangala',
    description: 'Day pass with fast Wi-Fi, meeting pods and unlimited coffee.',
    tags: ['work', 'tech'],
    personas: ['professional'],
    rating: 4.3,
    cost: 600,
    x: 2.3,
    y: -5,
    opens: '08:00',
    closes: '22:00',
    durationMin: 180,
    crowd: 'low',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: false,
    plannable: true,
  },
  {
    id: 'cultfit',
    name: 'Cult.fit Indiranagar',
    category: 'place',
    area: 'Indiranagar',
    description: 'Drop-in gym and group classes with a single-day pass.',
    tags: ['fitness'],
    personas: ['professional'],
    rating: 4.2,
    cost: 499,
    x: 4,
    y: 0,
    opens: '06:00',
    closes: '22:00',
    durationMin: 60,
    crowd: 'medium',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'bal-bhavan',
    name: 'Jawahar Bal Bhavan',
    category: 'place',
    area: 'Cubbon Park',
    description: 'Toy train, play areas and a mini lake for younger kids.',
    tags: ['kids', 'nature'],
    personas: ['family'],
    rating: 4.2,
    cost: 20,
    x: -0.5,
    y: 0.3,
    opens: '10:00',
    closes: '17:30',
    durationMin: 60,
    crowd: 'medium',
    safety: 'high',
    accessible: true,
    outdoor: true,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'commercial-street',
    name: 'Commercial Street',
    category: 'place',
    area: 'Shivajinagar',
    description: 'Busy lanes of clothes, jewellery and street snacks at bargain prices.',
    tags: ['shopping', 'food'],
    personas: ['tourist', 'student', 'family'],
    rating: 4.1,
    cost: 800,
    x: 0.8,
    y: 1.6,
    opens: '10:30',
    closes: '21:00',
    durationMin: 75,
    crowd: 'high',
    safety: 'medium',
    accessible: false,
    outdoor: true,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'church-street',
    name: 'Church Street',
    category: 'place',
    area: 'Central',
    description: 'Bookshops, cafés and pubs on a cobbled pedestrian-friendly street.',
    tags: ['nightlife', 'food', 'art', 'shopping'],
    personas: ['student', 'professional', 'tourist'],
    rating: 4.4,
    cost: 500,
    x: 0.3,
    y: 0.2,
    opens: '10:00',
    closes: '23:00',
    durationMin: 60,
    crowd: 'high',
    safety: 'medium',
    accessible: true,
    outdoor: true,
    nearMetro: true,
    plannable: true,
  },
  {
    id: 'manipal-hospital',
    name: 'Manipal Hospital',
    category: 'service',
    area: 'Old Airport Road',
    description: '24/7 multi-speciality hospital with emergency care and pharmacy.',
    tags: ['hospital'],
    personas: ['family', 'tourist', 'professional', 'student'],
    rating: 4.3,
    cost: 0,
    x: 5,
    y: -1,
    opens: '00:00',
    closes: '23:59',
    durationMin: 0,
    crowd: 'medium',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: false,
  },
  {
    id: 'mg-road-metro',
    name: 'MG Road Metro Station',
    category: 'service',
    area: 'MG Road',
    description: 'Purple Line hub. Get a travel card at the counter for cheaper fares.',
    tags: ['transit'],
    personas: ['student', 'professional', 'tourist'],
    rating: 4.2,
    cost: 30,
    x: 0.4,
    y: 0.5,
    opens: '05:00',
    closes: '23:00',
    durationMin: 0,
    crowd: 'medium',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: true,
    plannable: false,
  },
  {
    id: 'apollo-pharmacy',
    name: 'Apollo Pharmacy 24/7',
    category: 'service',
    area: 'Richmond Road',
    description: 'Round-the-clock pharmacy with essentials and first-aid supplies.',
    tags: ['hospital'],
    personas: ['family', 'tourist', 'student', 'professional'],
    rating: 4.1,
    cost: 0,
    x: 0.6,
    y: -0.8,
    opens: '00:00',
    closes: '23:59',
    durationMin: 0,
    crowd: 'low',
    safety: 'high',
    accessible: true,
    outdoor: false,
    nearMetro: false,
    plannable: false,
  },
]
